### ISSUE TITLE
left & right disparity map

### ISSUE THREAD

**Issue by GongXinyuu** [lmb-freiburg/dispnet-flownet-docker#1]
Hi, is it possible to get left and right disparity map?

**Comment by nikolausmayer** [comment]
Our datasets contain both.

The DispNet only estimates the left disparity map. To get a right disparity map, rotate both images by 180°, feed them into the network in reverse order (right-rotated+left-rotated instead of left+right), and rotate the output by 180° again. But you won't get any consistency benefits from that ;)

**Comment by GongXinyuu** [comment]
Thank U very much!
