### ISSUE TITLE
DummyData layer in train prototxt file

### ISSUE THREAD

**Issue by adhara123007** [lmb-freiburg/dispnet-flownet-docker#15]
Hi,

I was looking at the dummy data layer in train.prototxt file of DispNetCorr1D.
I had a few questions.
1. What is the need for it?
2. How does this work ?
3. As I understand, the dummy data layer creates additional blob and concatenates it. But the slice layer that follows has a slice point 1. That means actually the ground truth doesn't go through the network.

**Comment by nikolausmayer** [comment]
The `FlowAugmentation` layer which we use in this DispNet was designed for optical flow and needs 2-layer inputs. Instead of rewriting it to deal with single-layer disparity input as a special case, we just pad the disparity with a second dummy layer of zeroes. This works because the disparity map is a valid x-flow component (remember that disparity is just a special case of optical flow).
The output of the `FlowAugmentation` layer is again a 2-layer (augmented) flow map, from which we get the augmented disparity map by discarding the previously added dummy layer.

The augmentation parameters ensure that this process does not perform steps which would invalidate the disparity setting.

**Comment by adhara123007** [comment]
thanks
