### ISSUE TITLE
EPE evaluation

### ISSUE THREAD

**Issue by OzzyW** [lmb-freiburg/dispnet-flownet-docker#8]
Hi again,

I was wondering on which images the EPE evaluation was done on (can you confirm it was these -
https://github.com/lmb-freiburg/flownet2/issues/154) and if every pixel in the image was considered?

Have a nice weekend! :)

**Comment by nikolausmayer** [comment]
Hi! I did my best to reconstruct the collection of images. It is a heuristic, not the groundtruth (the original selection was lost, and a simple bruteforce check is impossible because the released dataset and our own version do not use the exact same compression scheme), but I think chances are good that no wrong sample was selected.

We used every pixel from every sample for our EPE numbers.

**Comment by OzzyW** [comment]
I understand, Thanks for the reconstruction! :)
